### ISSUE TITLE
closed alpha checklist

### ISSUE THREAD

**Issue by zaknaj** [dabateam/daba#1]
# closed alpha checklist

### bugs / to fix
- [x] fix issue with docker not correctly detecting runtime / socket path to use
- [ ] get project status before re-routing to project page to avoid flicker (after `create project` loading) 
- [ ] stopping apps or projects causes a flicker
- [ ] pulsing green lights go out of sync
- [x] show `app name` instead of `tech` in loading screen
- [x] sentry to get logs remotely
  - [ ] figure out issue with this error `EXC_BAD_ACCESS / KERN_INVALID_ADDRESS / 0x0` showing only on sentry (not locally)
  - [ ] re-enable sentry, but only in production
- [ ] revert port to random, or try to actually get an empty port
- [ ]  delete should include volumes / networks
- [ ] already existing images don't show done in loading screen (e.g. mongodb since it's declared by docker-compose)
- [ ] remove `new project` routes: should be local state
- [ ] make logs selectable 
- [ ] header: click on steps: logic

### features
- [x] ~~automatically install docker if not installed (colima)~~
  - [x] > set dockerode socket path correctly
- [x] delete confirmation
- [ ] open logs
- [ ] open shell
- [ ] open in finder
- [ ] open in editor (vscode ?)
- [x] avoid port collision when assigning ports
  - [x] > detect used ports
- [x] [wip] better loading screen/flow/more infos
- [ ] fix app icons, title, description, etc...
- [ ] setup basic analytics
- [ ] write readme
- [x] confirmation on `create project` cancel (if some data is set)
- [ ] put download link for latest release in website
  - [ ] change generated name for downloadable (remove version)
- [x] save logs in file for remote debugging
  - [x] check if patching `console.log` in main/index patches it globally
- [x] remake create project flow (should follow steps + hide sidemenu)
- [ ] loading done screen
  - [ ] confetti
  - [ ] "finishing touches" after all apps loaded
  - [ ] go to project dashboard
- [x] esc to exit `create project` modal
- [x] `x` icon to cancel/exit `create project` modal
- [ ] `Homepage` link
- [ ] tags/filters on starter search

### nice to have
- [ ] fading overlay over starters when list is long (to show you can scroll)
- [ ] better `app auto-update` flow (maybe promt, no auto-install?)
- [ ] use fonts from local (no google fonts)
- [ ] view template details (description, technologies, tags, ...)
- [ ] smoother progress for concrete steps (e.g. 3/4 to 4/4)
- [ ] auto scroll logs to last log if user is scrolled to the bottom
- [x] fix max width/height of `create project` modal
- [ ] min height/width of browserwindow (to give create project modal space)
- [ ] left click -> context menu on projects
- [x] remove "flow" from list of steps
- [x] delete modal -> enter to submit
- [ ] copy log lines

### starters, apps
- [ ] react
- [ ] vue
- [ ] svelte
- [ ] mongo
- [ ] postgres
- [ ] mysql
- [ ] python/django
- [ ] php/laravel ?
- [ ] node/express
- [ ] go / ruby / java / ...
- [ ] starters -> prepare 3 or more (fe+be+db)
